In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://soax.com/research/time-spent-on-social-media"

response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')

    table = soup.find('tbody')

    years = []
    minutes_per_day = []
    changes = []

    for row in table.find_all('tr'):
        cells = row.find_all('td')
        if cells:  
            years.append(cells[0].text.strip())
            minutes_per_day.append(cells[1].text.strip())
            changes.append(cells[2].text.strip())

    data = {
        'Year': years,
        'Minutes / day': minutes_per_day,
        'Change': changes
    }
    mpd = pd.DataFrame(data)

In [3]:
mpd

    Year Minutes / day    Change
0   2024           143   ↓ -5.3%
1   2023           151   ↑ 2.72%
2   2022           147   ↑ 1.38%
3   2021           145      ↓ 0%
4   2020           145      ↓ 0%
5   2019           145   ↑ 2.11%
6   2018           142   ↑ 5.97%
7   2017           134   ↑ 4.69%
8   2016           128  ↑ 15.32%
9   2015           111   ↑ 6.73%
10  2014           104   ↑ 9.47%
11  2013            95   ↑ 5.56%
12  2012            90         –